// Generated by Xata Codegen 0.27.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "sets",
    columns: [
      { name: "title", type: "string" },
      { name: "description", type: "string" },
      { name: "private", type: "bool" },
      { name: "cards", type: "int" },
      { name: "creator", type: "string" },
    ],
    revLinks: [
      { column: "set", table: "learnings" },
      { column: "set", table: "user_sets" },
    ],
  },
  {
    name: "cardsCapitals",
    columns: [
      { name: "question", type: "string" },
      { name: "answer", type: "string" },
      { name: "set", type: "string" },
    ],
  },
  {
    name: "cardsProgramming",
    columns: [
      { name: "question", type: "string" },
      { name: "answer", type: "string" },
      { name: "set", type: "string" },
    ],
  },
  {
    name: "learnings",
    columns: [
      { name: "set", type: "link", link: { table: "sets" } },
      { name: "user", type: "string" },
      { name: "cards_total", type: "int" },
      { name: "cards_correct", type: "int" },
      { name: "cards_wrong", type: "int" },
      { name: "score", type: "float" },
    ],
  },
  {
    name: "user_sets",
    columns: [
      { name: "user", type: "string" },
      { name: "set", type: "link", link: { table: "sets" } },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Sets = InferredTypes["sets"];
export type SetsRecord = Sets & XataRecord;

export type CardsCapitals = InferredTypes["cardsCapitals"];
export type CardsCapitalsRecord = CardsCapitals & XataRecord;

export type CardsProgramming = InferredTypes["cardsProgramming"];
export type CardsProgrammingRecord = CardsProgramming & XataRecord;

export type Learnings = InferredTypes["learnings"];
export type LearningsRecord = Learnings & XataRecord;

export type UserSets = InferredTypes["user_sets"];
export type UserSetsRecord = UserSets & XataRecord;

export type DatabaseSchema = {
  sets: SetsRecord;
  cardsCapitals: CardsCapitalsRecord;
  cardsProgramming: CardsProgrammingRecord;
  learnings: LearningsRecord;
  user_sets: UserSetsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://chandra-reddy-s-workspace-3tihjo.us-east-1.xata.sh/db/learning-app",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
